<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MenuList.aspx.cs" Inherits="Assessment1.MenuList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <h2>Menu Items List</h2>

    <asp:GridView ID="gvMenu" runat="server"
        AutoGenerateColumns="false"
        DataKeyNames="MenuId"
        OnRowCommand="gvMenu_RowCommand"
        OnRowDeleting="gvMenu_RowDeleting"
        AutoGenerateDeleteButton="false">

        <Columns>
            <asp:BoundField DataField="Name" HeaderText="Name" />
            <asp:BoundField DataField="Price" HeaderText="Price" />

            <asp:ButtonField Text="View" CommandName="View" />
            <asp:ButtonField Text="Edit" CommandName="Edit" />
            <asp:ButtonField Text="Delete" CommandName="Delete" />
        </Columns>

    </asp:GridView>

</asp:Content>
