//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renewal
    {
        public int RenewalId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> NewEndDate { get; set; }
        public Nullable<decimal> RenewalAmount { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
