//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Policies = new HashSet<Policy>();
        }
    
        public int VehicleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string VehicleNumber { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> ManufactureYear { get; set; }
        public string EngineNumber { get; set; }
        public string ChassisNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policies { get; set; }
        public virtual User User { get; set; }
    }
}
