//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int ClaimId { get; set; }
        public int PolicyId { get; set; }
        public decimal ClaimAmount { get; set; }
        public string ClaimReason { get; set; }
        public string ClaimStatus { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
